# Generated by Django 3.1.1 on 2020-11-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Character', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
