# Generated by Django 3.1.1 on 2020-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='surnames',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
