# Generated by Django 3.1.1 on 2020-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contributors_surnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='github',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
